LABEL eu.simphony-project.docker.type="webapp" \
      eu.simphony-project.docker.env.user="" \
      eu.simphony-project.docker.env.jpy-user="" \
      eu.simphony-project.docker.env.jpy-base-user-url="" \
      eu.simphony-project.docker.env.url-id=""

COPY container-files/ /

WORKDIR /root

# These are required for the remote access to the docker container
EXPOSE 8888
ENTRYPOINT ["/startup.sh"]
